#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamBindingSample.Resource", IsApplication=true)]

namespace XamBindingSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050021
			public const int AddButton = 2131034145;
			
			// aapt resource value: 0x7f050023
			public const int BindingsButton = 2131034147;
			
			// aapt resource value: 0x7f05001e
			public const int ButtonsPanel = 2131034142;
			
			// aapt resource value: 0x7f050024
			public const int CommandsButton = 2131034148;
			
			// aapt resource value: 0x7f050016
			public const int CustomEventEditText = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int DynamicParameterButton = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int ItemCheck = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int ItemText = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int LayoutRoot = 2131034137;
			
			// aapt resource value: 0x7f050025
			public const int ListsButton = 2131034149;
			
			// aapt resource value: 0x7f050001
			public const int MyButtonA1 = 2131034113;
			
			// aapt resource value: 0x7f050012
			public const int MyButtonJ1 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int MyCheckBox = 2131034132;
			
			// aapt resource value: 0x7f050002
			public const int MyCheckBoxA1 = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int MyCheckBoxC1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int MyCheckBoxC2 = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int MyCheckBoxF1 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int MyCheckBoxG1 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int MyCheckBoxH1 = 2131034127;
			
			// aapt resource value: 0x7f050017
			public const int MyEditText = 2131034135;
			
			// aapt resource value: 0x7f050003
			public const int MyEditTextB1 = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int MyEditTextD1 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int MyEditTextE1 = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int MyEditTextF1 = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int MyEditTextG1 = 2131034126;
			
			// aapt resource value: 0x7f05001c
			public const int MyRecycler = 2131034140;
			
			// aapt resource value: 0x7f050004
			public const int MyTextViewB1 = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int MyTextViewD1 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int MyTextViewE1 = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int MyTextViewH1 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int MyTextViewJ1 = 2131034129;
			
			// aapt resource value: 0x7f050022
			public const int RemoveButton = 2131034146;
			
			// aapt resource value: 0x7f05001d
			public const int SelectedItemNamePanel = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int SelectedItemNameText = 2131034143;
			
			// aapt resource value: 0x7f050013
			public const int SimpleCommandButton = 2131034131;
			
			// aapt resource value: 0x7f050015
			public const int StaticParameterButton = 2131034133;
			
			// aapt resource value: 0x7f050020
			public const int ToggledItemsText = 2131034144;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Bindings = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Commands = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ItemTemplate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Lists = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int BindingTextStyle = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int ButtonStyle = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int CheckBoxStyle = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int EditTextStyle = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int LabelStyle = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int SeparatorStyle = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int SmallBindingTextStyle = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int SmallButtonStyle = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int SubSeparatorStyle = 2131165190;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
